apiVersion: v1

kind: ConfigMap

metadata:
  name: app-config

data:
  RECOMMENDATION_SERVICE: "http://recommendation-service:8001"
  USER_SERVICE: "http://user-service:8002"
  FEEDBACK_SERVICE: "http://feedback-service:8003"